<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SZDJZBDT0105" name="demo1.Invocation" tests="1" failures="0" timestamp="18 一月 2019 01:56:28 GMT" time="4.912" errors="1">
  <testcase name="loginTest" time="4.912" classname="demo1.Invocation">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method demo1.Invocation.loginTest() didn&#039;t finish within the time-out 4900">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method demo1.Invocation.loginTest() didn't finish within the time-out 4900
at sun.misc.Unsafe.compareAndSwapInt(Native Method)
at java.util.concurrent.atomic.AtomicInteger.compareAndSet(AtomicInteger.java:133)
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:711)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1014)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- loginTest -->
</testsuite> <!-- demo1.Invocation -->
